/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "description_for_thrift_constants.h"



const description_for_thriftConstants g_description_for_thrift_constants;

description_for_thriftConstants::description_for_thriftConstants() {
}



