/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef description_for_thrift_CONSTANTS_H
#define description_for_thrift_CONSTANTS_H

#include "description_for_thrift_types.h"



class description_for_thriftConstants {
 public:
  description_for_thriftConstants();

};

extern const description_for_thriftConstants g_description_for_thrift_constants;



#endif
